name: PowerSigns
main: com.ricochet1k.bukkit.powersigns.PowerSigns
version: 1.1.4
authors: [ricochet1k, KoryuObihiro]
description: |
    Give your signs Power!

commands:
  powersigns:
    aliases: [ps]
    description: Allows control of PowerSigns.
    usage: |
           /<command> debug snow | Toggles debugging snowballs
           /<command> debug rightclick|rc | Toggles right-click debugging of PowerSigns.
           /<command> debug add [name] | Adds debugging to the sign so you see why it fails.
           /<command> debug del [name] | Deletes debugging from the sign.
           /<command> debug clear | Clears all debugging signs.
